const WORDS = [
  {word:"anxious", meaning:"불안한", part:"adjective"},
  {word:"relieved", meaning:"안도한", part:"adjective"},
  {word:"frustrated", meaning:"좌절한", part:"adjective"},
  {word:"confident", meaning:"자신감 있는", part:"adjective"},
  {word:"jealous", meaning:"질투하는", part:"adjective"},
  {word:"patient", meaning:"참을성 있는", part:"adjective"},
  {word:"stubborn", meaning:"고집 센", part:"adjective"},
  {word:"curious", meaning:"궁금해하는", part:"adjective"},
  {word:"timid", meaning:"소심한", part:"adjective"},
  {word:"generous", meaning:"관대한", part:"adjective"},
  {word:"selfish", meaning:"이기적인", part:"adjective"},
  {word:"cheerful", meaning:"명랑한", part:"adjective"},
  {word:"grumpy", meaning:"투덜거리는", part:"adjective"},
  {word:"ashamed", meaning:"창피한", part:"adjective"},
  {word:"proud", meaning:"자랑스러운", part:"adjective"},
  {word:"miserable", meaning:"비참한", part:"adjective"},
  {word:"delighted", meaning:"아주 기쁜", part:"adjective"},
  {word:"disappointed", meaning:"실망한", part:"adjective"},
  {word:"determined", meaning:"결심한", part:"adjective"},
  {word:"loyal", meaning:"충직한", part:"adjective"},
  {word:"sympathetic", meaning:"동정하는", part:"adjective"},
  {word:"hesitant", meaning:"망설이는", part:"adjective"},
  {word:"enthusiastic", meaning:"열정적인", part:"adjective"},
  {word:"panic", meaning:"당황하다", part:"verb"},
  {word:"admire", meaning:"존경하다", part:"verb"},
  {word:"envy", meaning:"부러워하다", part:"verb"}
];