const WORDS=[
{word:"anxious",meaning:"불안한"},
{word:"relieved",meaning:"안도한"},
{word:"frustrated",meaning:"좌절한"},
{word:"confident",meaning:"자신감 있는"},
{word:"jealous",meaning:"질투하는"},
{word:"patient",meaning:"참을성 있는"},
{word:"stubborn",meaning:"고집 센"},
{word:"curious",meaning:"궁금해하는"},
{word:"timid",meaning:"소심한"},
{word:"generous",meaning:"관대한"},
{word:"selfish",meaning:"이기적인"},
{word:"cheerful",meaning:"명랑한"},
{word:"grumpy",meaning:"투덜거리는"},
{word:"ashamed",meaning:"창피한"},
{word:"proud",meaning:"자랑스러운"},
{word:"miserable",meaning:"비참한"},
{word:"delighted",meaning:"아주 기쁜"},
{word:"disappointed",meaning:"실망한"},
{word:"determined",meaning:"결심한"},
{word:"loyal",meaning:"충직한"},
{word:"sympathetic",meaning:"동정하는"},
{word:"hesitant",meaning:"망설이는"},
{word:"enthusiastic",meaning:"열정적인"},
{word:"panic",meaning:"당황하다"},
{word:"admire",meaning:"존경하다"},
{word:"envy",meaning:"부러워하다"}
];
